### ISSUE TITLE
Production Version

### ISSUE THREAD

**Issue by Farouk-Alhraki-ACC** [singlestore-labs/singlestoredb-python#13]
It would be nice to get a production version sometime soon and having more devs actually work on this. 
Having only one guy work on this for the past 6 months makes me not want to use it.

**Comment by pranavaurora** [comment]
Thanks for this feedback. We are committed to getting our V1 shipped very soon. The driver itself is very stable and we're focussed bundling on some new features that will enhance usage like:

- UDFs 
- Interacting with the management API with SQL

The driver is based on PyMySQL which we merge new versions in from time to time. This is an important area for us and we will be adding more functionality down the line.

**Comment by kesmit13** [comment]
We have reached production releases.
